# Linear Algebra in python NOTES!

In [1]:
import numpy as np

In [2]:
v1 = np.array([1,2,3]) # this is a 3 dimentional vector
v2 = np.array([4,5,6])

In [3]:
print(v1)
print(v2)

[1 2 3]
[4 5 6]


## vector operations 

vector addition and subtraction

In [4]:
v_add = v1 + v2
v_sub = v1 - v2
print("v1 + v2:", v_add)
print("v1 - v2:", v_sub)

v1 + v2: [5 7 9]
v1 - v2: [-3 -3 -3]


vector multiplication

In [5]:
scalar = 2
v_scaled = v1*scalar
print(v_scaled)

[2 4 6]


In [6]:
dot_product = np.dot(v1,v2)
#1*4 + 2*5 + 3*6 = 36
print(dot_product)

32


Magnitude (Norm) of a Vector: The magnitude (or length) of a vector 𝑣1 is the square root of the sum of the squares of its elements.

In [7]:
magnitude = np.linalg.norm(v1)
print("Magnitude of v1:", magnitude)


Magnitude of v1: 3.7416573867739413


## matrices and matric operations

In [8]:
#creating one
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[7,8,9], [10,11,12],  [13,14,15]])
print(A)
print()
print(B)

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]
 [13 14 15]]


addition and subrsubtraction|

In [9]:
C = np.array([[1, 2, 3], [4, 5, 6]])
matrix_add = A + C
matrix_sub = A - C
print("A + C:\n", matrix_add)
print("A - C:\n", matrix_sub)

A + C:
 [[ 2  4  6]
 [ 8 10 12]]
A - C:
 [[0 0 0]
 [0 0 0]]


multiplictaion - the dot product of the rows with the first column of the second matrix

In [10]:
# Multiplying A (2x3) and B (3x3)
print("A")
print(A)
print("B")
print(B)
print()
matrix_mul = np.dot(A, B) # Or A @ B
print("A * B:\n", matrix_mul)

A
[[1 2 3]
 [4 5 6]]
B
[[ 7  8  9]
 [10 11 12]
 [13 14 15]]

A * B:
 [[ 66  72  78]
 [156 171 186]]


transpose a matrix swaps its rows with its colums

In [11]:
transpose_A = A.T
print("Transpose of A:\n", transpose_A)


Transpose of A:
 [[1 4]
 [2 5]
 [3 6]]


Solving systems - y=mx+b
Where:
A is the coefficient matrix,
x is the vector of unknowns,
b is the constant vector.

2x + 3y = 5
4x - y = 3

In [12]:
# Coefficient matrix A and constant vector b
A = np.array([[2, 3], [4, -1]]) #unknonwns: first row are x and second row is y
b = np.array([5, 3]) # the left hande sides!
# Solve the system A * x = b
x = np.linalg.solve(A, b)
print("Solution (x, y):", x)


Solution (x, y): [1. 1.]


## Eigenvalues and Eigenvectors
in a squar matrix A, there is a 𝜆, scalar and a vector, v where
𝐴𝑣 = 𝜆𝑣

Then 𝜆 is an eigenvalue of 𝐴, and 𝑣 is the corresponding eigenvector.

Eigenvectors are directions that don’t change direction when a matrix acts on them.
    

Eigenvalues tell you how much those directions get stretched or squished.


1. Solving systems of differential equations
    - If eigenvalues are negative → system decays
    - Positive → system grows
    - Complex → oscillations
2. Data Science & Machine Learning (PCA)
    - Eigenvectors = directions of maximum variance in data
    - Eigenvalues = how important each direction is
3. Stability & convergence in Numerical Methods
    - If spectral radius < 1 → converges
    - Eigenvalues explain why some methods blow up and others behave nicely.
4. Vibrations & modes (physics & engineering)
    - Eigenvectors = natural vibration modes
    - Eigenvalues = frequencies
5. Image processing & computer graphics
    - Eigenvectors capture dominant patterns in images.
6. Google & networks (PageRank!)
    - Eigenvector = “importance” of a webpage
    - Eigenvalue = how stable that ranking is
7.  Matrix powers & fast computation
    - Diagonalizing a matrix = using eigenvalues to simplify hard problems.


### Eigenvectors are the “special directions” a system naturally likes to move in.
### Eigenvalues tell you whether motion in those directions grows, shrinks, or oscillates.


How to solve them in the Python???

In [13]:
A = np.array( [[2,1], [1,2]])

eigenvalues, eigenvectors = np.linalg.eig(A) #eig returns the values and vectors
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues: [3. 1.]
Eigenvectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


The inverse of a matrix A multiplied by the A is the identiry matrix

In [14]:
# Define a matrix
A = np.array([[4, 7], [2, 6]])

# Compute the inverse of A
A_inv = np.linalg.inv(A)
print("Inverse of A:\n", A_inv)

# Verify: A * A_inv should be the identity matrix
identity = np.dot(A, A_inv)
print("A * A_inv:\n", identity)

Inverse of A:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
A * A_inv:
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


what is a identiy matrix?
zeros everywhere but the diagonal

## Singular Value Decomposition (SVD)
Singular Value Decomposition (SVD) is a factorization of a matrix into three matrices:

A=UΣV T

Where:
- U and V are orthogonal matrices - where the transpose is the same!
- Σ is a diagonal matrix of singular values

SVD is useful in many applications such as data compression, image processing, and dimensionality reduction

In [15]:

# Define a matrix
A = np.array([[1, 2], [3, 4], [5, 6]])

# Perform SVD
U, sigma, Vt = np.linalg.svd(A)

print("U matrix:\n", U)
print("Sigma values:", sigma)
print("V^T matrix:\n", Vt)

U matrix:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Sigma values: [9.52551809 0.51430058]
V^T matrix:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


# Gaussian Elimination, Python

Steps:
1. Represent the system in matrics form
2. Forward elimination 
    Identify the pivot element (The pivot element is the first non-zero element in the current column that hasn't been eliminated)
   -  Swap rows if the pivot element is 0
   - Normalize the pivot
   -  Eliminate lower elements
   -  Move to the next col;um
3. Backward Substitution
   -  Start with the Last Equation
   -  Substitute and Solve
   - Repeat this process, moving upwards row by row, substituting known values into previous equations.
   -  Continue Until All Variables Are Solved
4. Interpret the Results
   -  Check for Consistency


Rules:
1. You can multiply any row by a constant (other than zero).
2. You can swap any two rows.
3. You can add two rows together.


In [16]:
import numpy as np

def gaussian_elimination(A, b):
    n = len(b)
    # Forward elimination
    for i in range(n):
        # Pivoting
        max_row = max(range(i, n), key=lambda x: abs(A[x][i]))
        A[i], A[max_row] = A[max_row], A[i]
        b[i], b[max_row] = b[max_row], b[i]
        
        # Make the rows below this one 0 in current column
        for j in range(i + 1, n):
            ratio = A[j][i] / A[i][i]
            A[j] = [A[j][k] - ratio * A[i][k] for k in range(n)]
            b[j] -= ratio * b[i]
    
    # Backward substitution
    x = [0] * n
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - sum(A[i][j] * x[j] for j in range(i + 1, n))) / A[i][i]
    return x

In [17]:
# Example Usage
A = [[2, 5, -1], [4, -2, 2], [-2, 1, 2]]
b = [5, 6, -1]
solution = gaussian_elimination(A, b)
print(f"Solution: {solution}")


Solution: [1.4444444444444444, 0.5555555555555555, 0.6666666666666666]


In [18]:
#check solutions
ans = np.linalg.solve(A,b) #this does the exact same thing
print(ans)

[1.44444444 0.55555556 0.66666667]


# LU Decomposition

a mathematical method used to factor a given square matrix A into the product of two matrices: a lower triangular matrix L and an upper triangular matrix U. 
- helpful for solving systemss, inverting matrices, and compyting determinants

big idea: breaking a porblem up into 2 easier problems


A=LU

L - a lower triangulare matrix (everything above diag is 0)
U - a upper triangler (everything below diag is 0)


Ly=b
Ux=y


key concepts!!!
    -matrix factorization
    - Simplifies the computation of matrix inverses and determinants.
    -  LU decomposition with partial pivoting

## Steps

1. intialize L as a identiy matrix(all zeros and 1s) and U as a copy of A
2. for each column
    preform a elimination below the pivot element to gets 0s

The formulia is UGLYYYY but the algorithm is simple

In [19]:
import numpy as np

def lu_decomposition(A):
    n = len(A)
    L = np.eye(n)  # Initialize L as an identity matrix
    U = np.array(A, dtype=float)  # Copy of A to avoid
    # modifying the original matrix
    # modifying the original matrix
    
    for i in range(n):
        # Eliminate elements below the pivot (U[i, i])
        for j in range(i+1, n):
            if U[i, i] == 0:
                raise ValueError("Zero pivot encountered. LU decomposition cannot proceed.")
        factor = U[j, i] / U[i, i]  # Multiplier for row
         # operation
        L[j, i] = factor  # Store multiplier in L

                # Update the rows of U
        for k in range(i, n):
                U[j, k] -= factor * U[i, k]

    return L, U

In [20]:
# Example usage
A = np.array([[2, 3, 1],[4, 7, -1],[-2, 1, 2]])

L, U = lu_decomposition(A)

print("Matrix A:\n", A)
print("Lower Triangular Matrix L:\n", L)
print("Upper Triangular Matrix U:\n", U)

Matrix A:
 [[ 2  3  1]
 [ 4  7 -1]
 [-2  1  2]]
Lower Triangular Matrix L:
 [[ 1.          0.          0.        ]
 [ 0.          1.          0.        ]
 [-1.          0.57142857  1.        ]]
Upper Triangular Matrix U:
 [[ 2.  3.  1.]
 [ 4.  7. -1.]
 [ 0.  0.  0.]]


#### NOTE: LU decomposition isn't directly available in NumPy but can be computed using the scipy.linalg package).

In [21]:
from scipy.linalg import lu

# Perform LU Decomposition
A = np.array([[2, 3, 1],
[4, 7, -1],
[-2, 1, 2]])

P, L, U = lu(A)
print("Matrix A:\n", A)
print("Permutation Matrix P:\n", P)
print("Lower Triangular Matrix L:\n", L)
print("Upper Triangular Matrix U:\n", U)


Matrix A:
 [[ 2  3  1]
 [ 4  7 -1]
 [-2  1  2]]
Permutation Matrix P:
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
Lower Triangular Matrix L:
 [[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [ 0.5        -0.11111111  1.        ]]
Upper Triangular Matrix U:
 [[ 4.          7.         -1.        ]
 [ 0.          4.5         1.5       ]
 [ 0.          0.          1.66666667]]


# Iterive methods!!!

idea: take a guess and compaire resluts and then refining the guess then repeat until the error is reasonably small

1. start with an initial guess - often all zeros or any resonable estimate
2. iterative update - updated based on previous iteration
3. convergence check - check if the solutions are simulare enough
4. stop

CONDITIONS:
- we want it to be diagonally dominate - the numbers in the diagonal to be bigger then anything in that row or column
        - can maniupuate with rules earler to make it this way
- symmetricly postively definite
    - producies positive numbers and close to merriorable


##### advantage: memory efficent, scaliblity, flexibility
##### disavantages : solver concergences based on starting guess, convergence depends on the matrix
