# Linear Algebra in python!

In [1]:
import numpy as np

In [3]:
v1 = np.array([1,2,3]) # this is a 3 dimentional vector
v2 = np.array([4,5,6])

In [4]:
print(v1)
print(v2)

[1 2 3]
[4 5 6]


## vector operations 

vector addition and subtraction

In [8]:
v_add = v1 + v2
v_sub = v1 - v2
print("v1 + v2:", v_add)
print("v1 - v2:", v_sub)

v1 + v2: [5 7 9]
v1 - v2: [-3 -3 -3]


vector multiplication

In [10]:
scalar = 2
v_scaled = v1*scalar
print(v_scaled)

[2 4 6]


In [12]:
dot_product = np.dot(v1,v2)
#1*4 + 2*5 + 3*6 = 36
print(dot_product)

32


Magnitude (Norm) of a Vector: The magnitude (or length) of a vector 𝑣1 is the square root of the sum of the squares of its elements.

In [14]:
magnitude = np.linalg.norm(v1)
print("Magnitude of v1:", magnitude)


Magnitude of v1: 3.7416573867739413


## matrices and matric operations

In [24]:
#creating one
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[7,8,9], [10,11,12],  [13,14,15]])
print(A)
print()
print(B)

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]
 [13 14 15]]


addition and subrsubtraction|

In [25]:
C = np.array([[1, 2, 3], [4, 5, 6]])
matrix_add = A + C
matrix_sub = A - C
print("A + C:\n", matrix_add)
print("A - C:\n", matrix_sub)

A + C:
 [[ 2  4  6]
 [ 8 10 12]]
A - C:
 [[0 0 0]
 [0 0 0]]


multiplictaion - the dot product of the rows with the first column of the second matrix

In [26]:
# Multiplying A (2x3) and B (3x3)
print("A")
print(A)
print("B")
print(B)
print()
matrix_mul = np.dot(A, B) # Or A @ B
print("A * B:\n", matrix_mul)

A
[[1 2 3]
 [4 5 6]]
B
[[ 7  8  9]
 [10 11 12]
 [13 14 15]]

A * B:
 [[ 66  72  78]
 [156 171 186]]


transpose a matrix swaps its rows with its colums

In [27]:
transpose_A = A.T
print("Transpose of A:\n", transpose_A)


Transpose of A:
 [[1 4]
 [2 5]
 [3 6]]


Solving systems - y=mx+b
Where:
A is the coefficient matrix,
x is the vector of unknowns,
b is the constant vector.

2x + 3y = 5
4x - y = 3

In [28]:
# Coefficient matrix A and constant vector b
A = np.array([[2, 3], [4, -1]]) #unknonwns: first row are x and second row is y
b = np.array([5, 3]) # the left hande sides!
# Solve the system A * x = b
x = np.linalg.solve(A, b)
print("Solution (x, y):", x)


Solution (x, y): [1. 1.]


## Eigenvalues and Eigenvectors
in a squar matrix A, there is a 𝜆, scalar and a vector, v where
𝐴𝑣 = 𝜆𝑣

Then 𝜆 is an eigenvalue of 𝐴, and 𝑣 is the corresponding eigenvector.

Eigenvectors are directions that don’t change direction when a matrix acts on them.
    

Eigenvalues tell you how much those directions get stretched or squished.


1. Solving systems of differential equations
- If eigenvalues are negative → system decays
- Positive → system grows
- Complex → oscillations
2. Data Science & Machine Learning (PCA)
- Eigenvectors = directions of maximum variance in data
- Eigenvalues = how important each direction is
3. Stability & convergence in Numerical Methods
- If spectral radius < 1 → converges
- Eigenvalues explain why some methods blow up and others behave nicely.
4. Vibrations & modes (physics & engineering)
- Eigenvectors = natural vibration modes
- Eigenvalues = frequencies
5. Image processing & computer graphics
- Eigenvectors capture dominant patterns in images.
6. Google & networks (PageRank!)
- Eigenvector = “importance” of a webpage
- Eigenvalue = how stable that ranking is
7.  Matrix powers & fast computation
- Diagonalizing a matrix = using eigenvalues to simplify hard problems.


### Eigenvectors are the “special directions” a system naturally likes to move in.
### Eigenvalues tell you whether motion in those directions grows, shrinks, or oscillates.


How to solve them in the Python???

In [31]:
A = np.array( [[2,1], [1,2]])

eigenvalues, eigenvectors = np.linalg.eig(A) #eig returns the values and vectors
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues: [3. 1.]
Eigenvectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


The inverse of a matrix A multiplied by the A is the identiry matrix

In [32]:
# Define a matrix
A = np.array([[4, 7], [2, 6]])

# Compute the inverse of A
A_inv = np.linalg.inv(A)
print("Inverse of A:\n", A_inv)

# Verify: A * A_inv should be the identity matrix
identity = np.dot(A, A_inv)
print("A * A_inv:\n", identity)

Inverse of A:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
A * A_inv:
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


what is a identiy matrix?
zeros everywhere but the diagonal

## Singular Value Decomposition (SVD)
Singular Value Decomposition (SVD) is a factorization of a matrix into three matrices:

A=UΣV T

Where:
- U and V are orthogonal matrices - where the transpose is the same!
- Σ is a diagonal matrix of singular values

SVD is useful in many applications such as data compression, image processing, and dimensionality reduction

In [36]:

# Define a matrix
A = np.array([[1, 2], [3, 4], [5, 6]])

# Perform SVD
U, sigma, Vt = np.linalg.svd(A)

print("U matrix:\n", U)
print("Sigma values:", sigma)
print("V^T matrix:\n", Vt)

U matrix:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Sigma values: [9.52551809 0.51430058]
V^T matrix:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
